services:
  backend:
    container_name: github_analyzer_backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      DEPLOY_ENV: dev
      DEBUG: "True"
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true
    depends_on:
      - redis

  frontend:
    container_name: github_analyzer_frontend
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  redis:
    container_name: github_analyzer_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
