class GitHubGraphQLError(Exception): ...


class GitHubAuthenticationError(GitHubGraphQLError): ...


class GitHubTransportError(GitHubGraphQLError): ...


class GitHubResponseError(GitHubGraphQLError): ...


class GitHubRestError(Exception): ...


class GitHubRestNotFoundError(GitHubRestError): ...


class GitHubRestTransportError(GitHubRestError): ...


class GitHubRestResponseError(GitHubRestError): ...


class UserAnalysisError(Exception): ...


class UserNotFoundError(UserAnalysisError): ...
