class GitHubGraphQLError(Exception): ...


class GitHubAuthenticationError(GitHubGraphQLError): ...


class GitHubTransportError(GitHubGraphQLError): ...


class GitHubResponseError(GitHubGraphQLError): ...


class UserAnalysisError(Exception): ...


class UserNotFoundError(UserAnalysisError): ...
